#!/bin/sh
# Script for calling multiple routines on a project, typically prior to committing to a repository.

# Produce individual UFOs from Glyphs file
psfglyphs2ufo --nofea source/masters/PayapLanna.glyphs source/masters

./preflight
