#!/bin/sh
# Script for calling multiple routines on a project, typically prior to committing to a repository.

echo "Checking and normalizing Regular..."
# Do this before meta sync so we minimize problems in the Bold
psfnormalize -p checkfix=fix source/masters/PayapLanna-Regular.ufo -p scrlevel=V
psfnormalize -p checkfix=fix source/masters/PayapLanna-Bold.ufo -p scrlevel=V

psfsetglyphorder -i source/glyph_data.csv source/masters/PayapLanna-Regular.ufo

# Create WOFF metadata file
psfmakewoffmetadata -n PayapLanna -i org.sil.fonts -o source/PayapLanna-WOFF-metadata.xml source/masters/PayapLanna-Regular.ufo # --populateufowoff --force

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/PayapLanna.designspace -p scrlevel=V

echo "preflight completed!"
