#!/bin/sh
# script to convert .ufo to .glyphs file for GUI editing

echo "Generating glyphs file from current designspace and UFOs"
psfufo2glyphs source/PayapLannaGlyphs.designspace source/masters/PayapLanna.glyphs